Include <sys/reg.h> for __WORDSIZE on musl
Fix build failure on musl-based systems due to missing __WORDSIZE
declaration. On musl, __WORDSIZE is defined in <sys/reg.h>.

Fixes:
src/base/elf_mem_image.cc:95:18: error: '__WORDSIZE' was not declared in this scope
   95 | typedef ElfClass<__WORDSIZE> CurrentElfClass;
      |                  ^~~~~~~~~~

Co-authored-by: =?UTF-8?q?Karel=20Ko=C4=8D=C3=AD?= <cynerd@email.cz>