fix compiler error when NO_TCMALLOC_SAMPLES is defined
the error is:
src/malloc_backtrace.cc:51:5: error: redefinition of 'int tcmalloc::GrabBacktrace(void**, int, int)'
   51 | int GrabBacktrace(void** result, int max_depth, int skip_count) {
      |     ^~~~~~~~~~~~~
In file included from src/malloc_backtrace.cc:34:
src/malloc_backtrace.h:43:12: note: 'int tcmalloc::GrabBacktrace(void**, int, int)' previously defined here
   43 | inline int GrabBacktrace(void** result, int max_depth, int skip_count) { return 0; }

Signed-off-by: Olivier Langlois <olivier@trillion01.com>