Fix link of backtrace-alloc.
The backtrace alloc showed link issues of the form

```
bazel-out/k8-opt/bin/_objs/symbolize/backtrace-alloc.o:backtrace-alloc.cc:function tcmalloc::BTPagesAllocator::~BTPagesAllocator():(.text._ZN8tcmalloc16BTPagesAllocatorD2Ev+0xb): error: undefined reference to 'tcmalloc::LowLevelAlloc::PagesAllocator::~PagesAllocator()'
bazel-out/k8-opt/bin/_objs/symbolize/backtrace-alloc.o:backtrace-alloc.cc:function tcmalloc::BTPagesAllocator::~BTPagesAllocator():(.text._ZN8tcmalloc16BTPagesAllocatorD0Ev+0x17): error: undefined reference to 'tcmalloc::LowLevelAlloc::PagesAllocator::~PagesAllocator()'
bazel-out/k8-opt/bin/_objs/symbolize/backtrace-alloc.o:backtrace-alloc.cc:function tcmalloc::BTPagesAllocator::AllocateAsHeader(unsigned long):(.text._ZN8tcmalloc16BTPagesAllocator16AllocateAsHeaderEm+0xd): error: undefined reference to 'tcmalloc::LowLevelAlloc::GetDefaultPagesAllocator()'
bazel-out/k8-opt/bin/_objs/symbolize/backtrace-alloc.o:backtrace-alloc.cc:function tcmalloc::BTPagesAllocator::AllocateAsHeader(unsigned long):(.text._ZN8tcmalloc16BTPagesAllocator16AllocateAsHeaderEm+0x69): error: undefined reference to 'tcmalloc::LowLevelAlloc::GetDefaultPagesAllocator()'
...
```

This was due to not depending on a library that provided these
symbols.

Part of the problem is that the `:all_headers` target collects
all the headers but no actual implementations.
So this probably should be detangled more, but this PR at least
fixes the immediate build issue.

Signed-off-by: Henner Zeller <h.zeller@acm.org>