stacktrace_libgcc-inl.h: fix build for some ARM toolchains
On OpenWrt when bulding for arm_cortex-a15_neon-vpfv4 or
arm_cortex-a9_vfpv3-d16, the build errors out due to an undefined symbol
_URC_NORMAL_STOP. This usually happens when the required header
(typically <unwind.h>) is not included, or the toolchain's unwind
implementation does not provide this definition.

Error:
src/stacktrace_libgcc-inl.h: In function '_Unwind_Reason_Code libgcc_backtrace_helper(_Unwind_Context*, void*)':
src/stacktrace_libgcc-inl.h:69:12: error: '_URC_NORMAL_STOP' was not declared in this scope
   69 |     return _URC_NORMAL_STOP;
      |

A work-around is to use URC_END_OF_STACK.

Signed-off-by: graysky <therealgraysky AT proton DOT me>