Add empty virtual destructor to class with virtual methods.
Clang 3.5 has a warning about deleting objects with virtual methods
through non-virtual destructors which was triggered. I'm not sure
whether this actually creates any undefined or otherwise incorrect
behavior, but it seems like a good thing to fix regardless.

Example compiler warning:
third_party/gperftools/src/tests/profile-handler_unittest.cc:282:5: error:
  delete called on '(anonymous namespace)::BusyThread' that has virtual
  functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete busy_worker_;
    ^